export const VIDEOS_TYPES = {
    SET_TRENDING: 'videos/SET_TRENDING', 
    SET_SEARCH_RESULTS: 'videos/SET_SEARCH_RESULTS', 
    SET_CHANNELS: 'videos/SET_CHANNELS', 
    SET_PLAYLIST: 'videos/SET_PLAYLIST',
    SET_QUERY: 'videos/SET_QUERY', 
    SET_TYPE: 'videos/SET_TYPE', 
    SET_CURRENT_VIDEO: 'videos/SET_CURRENT_VIDEO', 
    SET_RELATED_VIDEOS: 'videos/SET_RELATED_VIDEOS', 
    SET_CURRENT_CHANNEL: 'videos/SET_CURRENT_CHANNEL', 
    SET_LOADING: 'videos/SET_LOADING'
}